package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;
import javafx.stage.Stage;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.ComboBox;

import javafx.event.Event;

import javafx.scene.control.DatePicker;

public class PatientController {
	@FXML
	private ComboBox<String> dept_search_name;
	@FXML
	private ComboBox<String> doctor_search_name;
	@FXML
	private ComboBox<String> available_doctor_times;
	@FXML
	private DatePicker doctor_search_date;
	@FXML
	private ComboBox<String> test_search_id;
	@FXML
	private Label doctor_id;
	@FXML
	private Label patient_id_1;
	@FXML
	private Label Doctor_ID_1;
	@FXML
	private Label Doctor_Name_1;
	@FXML
	private Label Department_1;
	@FXML
	private Label Date_1;
	@FXML
	private Label Time_1;
	@FXML
	private Label patient_id_2;
	@FXML
	private Label patient_id_3;
	@FXML
	private Label patient_id_4;
	@FXML
	private Label patient_id_5;
	@FXML
	private Label Doctor_ID_2;
	@FXML
	private Label Doctor_ID_3;
	@FXML
	private Label Doctor_ID_4;
	@FXML
	private Label Doctor_ID_5;
	@FXML
	private Label Doctor_Name_2;
	@FXML
	private Label Doctor_Name_3;
	@FXML
	private Label Doctor_Name_4;
	@FXML
	private Label Doctor_Name_5;
	@FXML
	private Label Department_2;
	@FXML
	private Label Department_3;
	@FXML
	private Label Department_4;
	@FXML
	private Label Department_5;
	@FXML
	private Label Date_2;
	@FXML
	private Label Date_3;
	@FXML
	private Label Date_4;
	@FXML
	private Label Date_5;
	@FXML
	private Label Time_2;
	@FXML
	private Label Time_3;
	@FXML
	private Label Time_4;
	@FXML
	private Label Time_5;
	@FXML
	private Label status_1;
	@FXML
	private Label status_2;
	@FXML
	private Label status_3;
	@FXML
	private Label status_4;
	@FXML
	private Label medicine_name;
	@FXML
	private Label status_5;
	@FXML
	private Label med_history;
	@FXML
	private Label username;
	@FXML
	private Label Name;
	@FXML
	private Label patient_id;
	@FXML
	private Label lab_report;
	@FXML
	private Label Age;
	@FXML
	private Label Gender;
	@FXML
	private Label weight;
	@FXML
	private Button logout_btn;
	@FXML
	private Label sum;
	@FXML
	private Label Height;
	ObservableList<String> items = FXCollections.observableArrayList();
	ObservableList<String> items_1 = FXCollections.observableArrayList();
	ObservableList<String> items_2 = FXCollections.observableArrayList();
	Alert a=new Alert(AlertType.INFORMATION);

	int pid;
	public void getPID(int id)
	{
		pid=id;
	}
	int i=0;
	int d_id;
	// Event Listener on ComboBox[#dept_search_name].onAction
	@FXML
	public void show_department(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#doctor_search_name].onAction
	@FXML
	public void show_doctor(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void find_doctor(ActionEvent event) {
		// TODO Autogenerated
	String dept=(String) dept_search_name.getSelectionModel().getSelectedItem();
	try{  
		Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","Sriganash@27");
		Statement stmt=con.createStatement(); 
		ResultSet rs=stmt.executeQuery("select * from doctor where department='"+dept+"';");
		while(rs.next())
		{
			String name=rs.getString(4);
			
			items.add(name);
			doctor_search_name.setItems(items);
			
		}
			
	
		con.close();
		
}
	catch(Exception e){ System.out.println(e);} 
	
	}
	// Event Listener on Button.onAction
	@FXML
	public void find_available_time(ActionEvent event) {
		// TODO Autogenerated
		try{  
			Class.forName("com.mysql.jdbc.Driver");  
			Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","Sriganash@27");
			Statement stmt=con.createStatement(); 
			String doc=(String) doctor_search_name.getSelectionModel().getSelectedItem();
			ResultSet rs=stmt.executeQuery("select time from appointment a,Doctor d where d.name='"+doc+"' and a.date='"+doctor_search_date.getValue()+"' order by date,time;");
			if(!rs.next())
			{
				items_1.addAll("10","11","12","02","03","04");
				available_doctor_times.setItems(items_1);
			}
			else
			{
				rs.previous();
				boolean flag1,flag2,flag3,flag4,flag5,flag6;
				flag1=flag2=flag3=flag4=flag5=flag6=false;
				while(rs.next())
				{
					int time=rs.getInt(4);
					if(time!=10 && !flag1)
					{
						items_1.add("10");
						flag1=true;
					}
					if(time != 11 && !flag2)
					{
						items_1.add("11");
						flag2=true;
					}
					if(time != 12 && !flag3)
					{
						items_1.add("12");
						flag3=true;
					}
					if(time != 2 && !flag4)
					{
						items_1.add("02");
						flag4=true;
					}
					if(time != 3 && !flag5)
					{
						items_1.add("03");
						flag5=true;
					}
					if(time != 4 && !flag6) 
					{
						items_1.add("04");
						flag6=true;
					}
					available_doctor_times.setItems(items_1);
				}
			}
			
				
			
		
			con.close();
			
	}
		catch(Exception e){ System.out.println(e);} 
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void book_the_appointment(ActionEvent event) {
		// TODO Autogenerated
		try{  
			Class.forName("com.mysql.jdbc.Driver");  
			Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","Sriganash@27");
			Statement stmt=con.createStatement(); 
			String doc=(String) doctor_search_name.getSelectionModel().getSelectedItem();
			ResultSet rs=stmt.executeQuery("select d_id from doctor where name='"+doc+"';");
			
			
			if(rs.next())
			{
				int id=rs.getInt(1);
				LocalDate i=doctor_search_date.getValue();
				int time=Integer.parseInt((String) available_doctor_times.getSelectionModel().getSelectedItem());
				stmt.executeUpdate("insert into appointment values("+pid+",'"+i+"',"+time+","+id+");");
				
				doctor_id.setText("Appointment Booked");
			}
				
			
			con.close();
			
			
	}
		catch(Exception e){ System.out.println(e);}
		
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void seach_test(ActionEvent event) {
		// TODO Autogenerated
		try{  
			Class.forName("com.mysql.jdbc.Driver");  
			Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","Sriganash@27");
			Statement stmt=con.createStatement(); 
			String test=(String) test_search_id.getSelectionModel().getSelectedItem();
			
			ResultSet rs5=stmt.executeQuery("select * from lab where test_name='"+test+"' and pid="+pid+" and status='complete';");
			if(rs5.next())
			{
				String s=rs5.getString(2);
				lab_report.setText(s);
			}
			else
			{
				lab_report.setText("No test result found......");
			}
			
			con.close();
			
			
	}
		catch(Exception e){ System.out.println(e);}
	}
	// Event Listener on Tab.onSelectionChanged
	@FXML
	public void show_medical_history(Event event) {
		// TODO Autogenerated
		try{  
			Class.forName("com.mysql.jdbc.Driver");  
			Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","Sriganash@27");
			Statement stmt=con.createStatement(); 
			
			
			ResultSet rs5=stmt.executeQuery("select * from patient where pid="+pid+";");
			if(rs5.next())
			{
				String s=rs5.getString(7);
				med_history.setText(s);
			}
			
			con.close();
			
			
	}
		catch(Exception e){ System.out.println(e);}
	}
	
	public void buy_medicine()
	{
		try{  
			Class.forName("com.mysql.jdbc.Driver");  
			Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","Sriganash@27");
			Statement stmt=con.createStatement(); 
			int k=0;
			medicine_name.setText("");
			ResultSet rs5=stmt.executeQuery("select name,price from buymed b,medicine m where b.m_id=m.m_id and b.pid="+pid+";");
			if(rs5.next())
			{
				rs5.previous();
				while(rs5.next())
				{
					String h=medicine_name.getText();
					medicine_name.setText(h+"\n"+rs5.getString(1));
					k=k+rs5.getInt(2);
				}
			}
			else
				medicine_name.setText("No medicine added yet.......");
			sum.setText(""+k);
			
			
			con.close();
			
			
	}
		catch(Exception e){ System.out.println(e);}
	}
	// Event Listener on Button.onAction
	@FXML
	public void Book_medicine(ActionEvent event) {
		// TODO Autogenerated
		
		if(i==0)
		{
			medicine_name.setText("Successfully purchased medicine");
			i=1;
		}
		else
			medicine_name.setText("Medicine already purchased....");
		
	}
	// Event Listener on Tab.onSelectionChanged
	@FXML
	public void show_appointment(Event event) {
		// TODO Autogenerated
		try{  
			Class.forName("com.mysql.jdbc.Driver");  
			Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","Sriganash@27");
			Statement stmt=con.createStatement(); 
			ResultSet rs=stmt.executeQuery("select a.pid,a.date,a.time,a.id,d.name from appointment a,doctor d where a.pid="+pid+" and a.id=d.d_id;");
			Doctor_ID_1.setText("");
			Date_1.setText("");
			Time_1.setText("");
			Doctor_Name_1.setText("");
			int i=0;
			while(rs.next())
			{
				String id=Doctor_ID_1.getText();
				String date=Date_1.getText();
				String time=Time_1.getText();
				String name1=Doctor_Name_1.getText();
				Doctor_Name_1.setText(name1+"\n"+rs.getString(5));
				Doctor_ID_1.setText(id+"\n"+rs.getInt(4));
				Date_1.setText(date+"\n"+rs.getDate(2));
				Time_1.setText(time+"\n"+rs.getInt(3));
			}
			
			ResultSet rs1=stmt.executeQuery("select name from doctor where d_id="+i+";");
			while(rs1.next())
			{
				String name=Doctor_Name_1.getText();
				Doctor_Name_1.setText(name+"\n"+rs.getInt(4));
			}
		
			
				
			
		
			con.close();
			
	}
		catch(Exception e){ System.out.println(e);}
		
	}
	// Event Listener on Tab.onSelectionChanged
	@FXML
	public void show_patient_profile(Event event) {
		// TODO Autogenerated
		try{  
			Class.forName("com.mysql.jdbc.Driver");  
			Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","Sriganash@27");
			Statement stmt=con.createStatement(); 
			ResultSet rs=stmt.executeQuery("select * from patient where pid="+pid+";");
			
			if(rs.next())
			{
				username.setText(rs.getString(2));
				Name.setText(rs.getString(4));
				patient_id.setText(""+rs.getInt(1));
				Age.setText(""+rs.getInt(5));
				Gender.setText(rs.getString(6));
				Height.setText(""+rs.getInt(8));
				weight.setText(""+rs.getInt(9));
			}
			
				
			
		
			con.close();
			
	}
		catch(Exception e){ System.out.println(e);}
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void Edit_patient_profile(ActionEvent event) {
		// TODO Autogenerated
	}

	
	@FXML
	public void logout_onclick(ActionEvent event) throws IOException {
		Parent login_parent = FXMLLoader.load(getClass().getResource("Sample.fxml"));
		Scene login_scene = new Scene(login_parent);
		login_scene.getStylesheets().add(getClass().getResource("loginapplication.css").toExternalForm());
		Stage login_stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		login_stage.setScene(login_scene);
		login_stage.show();
	}
	
	public void getLabReport()
	{
		try{  
			Class.forName("com.mysql.jdbc.Driver");  
			Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","Sriganash@27");
			Statement stmt=con.createStatement(); 
			ResultSet rs=stmt.executeQuery("select * from lab where pid="+pid+";");
			while(rs.next())
			{
				String test=rs.getString(1);
				items_2.add(test);
				test_search_id.setItems(items_2);
			}
			
			
				
			
		
			con.close();
			
	}
		catch(Exception e){ System.out.println(e);}
	}
	
	public void initialize()
	{
		dept_search_name.getItems().addAll("Cardiology","Radiology","Immediate medicine","Pediatric","Orthopedics","Gynacology","Therapist","Psychiartist","Nuerology");
	}
}
