package application;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;


public class SignUpController {
    @FXML
    private AnchorPane pLogin;
    @FXML
    private Label login_label;
    @FXML
    private TextField pusername_field;
    @FXML
    private TextField ppassword_field;
    @FXML
    private TextField add_name;
    @FXML
    private TextField add_age;
    @FXML
    private TextField add_gender;
    @FXML
    private TextField add_history;
    @FXML
    private TextField add_height;
    @FXML
    private TextField add_weight;
    @FXML
    private Button signup_btn;

    // Event Listener on Button[#signup_btn].onAction

    @FXML
    
    public void home_onclick(ActionEvent event) throws IOException
    {
    	Parent login_parent = FXMLLoader.load(getClass().getResource("Sample.fxml"));
		Scene login_scene = new Scene(login_parent);
		login_scene.getStylesheets().add(getClass().getResource("loginapplication.css").toExternalForm());
		Stage login_stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		login_stage.setScene(login_scene);
		login_stage.show();
    }
    public void signup_onclick(ActionEvent event) {
        // TODO Autogenerated
        String username = pusername_field.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "Sriganash@27");
            Statement stmt = con.createStatement();

            ResultSet rs=stmt.executeQuery("select * from patient where username='"+username+"';");
			if(rs.next())
			{
                Alert a = new Alert(Alert.AlertType.ERROR);
				a.setContentText("Username already exist  !!");
                a.show();
			}
			else
            {
                String password = ppassword_field.getText();
                String name = add_name.getText();
                int age = Integer.parseInt(add_age.getText());
                String gender = add_gender.getText();
                String history = add_history.getText();
                int height = Integer.parseInt(add_height.getText());
                int weight = Integer.parseInt(add_weight.getText());

                Random random = new Random();
                int id = random.nextInt(1000);


                stmt.executeUpdate("insert into patient values(" + id + ",'" + username + "','" + password + "','" + name + "'," + age + ",'" + gender + "','" + history + "'," + height + "," + weight + ");");
                Alert a = new Alert(Alert.AlertType.CONFIRMATION);
                a.setContentText("Inserted successfully.......");
                a.show();
		        FXMLLoader loader = new FXMLLoader();
		        loader.setLocation(getClass().getResource("PatientSample.fxml"));
		        Parent PatientParent = loader.load();
		        
		        Scene PatientScene = new Scene(PatientParent);
		        
		        
		        //access the controller and call a method
		        PatientController controller = loader.getController();
		        controller.getPID(id);
		        
		        //This line gets the Stage information
		        Stage window = (Stage)((Node)event.getSource()).getScene().getWindow();
		        
		        window.setScene(PatientScene);
		        window.show();
            }

            con.close();

        } catch (Exception e) {
            System.out.println(e);
        }
    }
}